name: Java Coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '20'

    - name: Build with Maven
      run: mvn clean install -DskipTests=false

    - name: Run tests and generate coverage report
      run: mvn test jacoco:report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # You need to add this secret to your repository settings

    - name: Cleanup
      run: mvn clean
